/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DAO.Buku;
import DAO.Item;
import Koneksi.Koneksi;
import Model.BukuModel;
import Objcet.ObjectClass;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HAMBA NOTEBOOK
 */
public class BukuFrame extends javax.swing.JFrame {
        BukuModel bukmodel;
        
    DefaultTableModel tableModelBuku = new DefaultTableModel();
    private BukuModel bukModel = new BukuModel();
    
    public BukuFrame() {
        initComponents();        
        ObjectClass.bukuMod.getAllUser();

        tableBuku.setModel(ObjectClass.bukuMod);
 
        buttonDeleteUser.setEnabled(true);
        buttonUpdateUser.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldStok = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        fieldIdBuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldHarga = new javax.swing.JTextField();
        buttonUpdateUser = new javax.swing.JButton();
        buttonDeleteUser = new javax.swing.JButton();
        buttonInsertUser = new javax.swing.JButton();
        fieldPengarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldJudul = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        buttonInsertUser1 = new javax.swing.JButton();
        produk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fieldIdKat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Stok Tersedia   :");

        jLabel7.setText("Harga Buku      :");

        tableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableBuku);

        jLabel2.setText("ID Buku          :");

        fieldIdBuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdBukActionPerformed(evt);
            }
        });

        jLabel4.setText("Judul               :");

        buttonUpdateUser.setText("Update");
        buttonUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateUserActionPerformed(evt);
            }
        });

        buttonDeleteUser.setText("Delete");
        buttonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteUserActionPerformed(evt);
            }
        });

        buttonInsertUser.setText("Insert");
        buttonInsertUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertUserActionPerformed(evt);
            }
        });

        jLabel9.setText("Pengarang      :");

        fieldJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJudulActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama Kategori     :");

        buttonInsertUser1.setText("BACK");
        buttonInsertUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertUser1ActionPerformed(evt);
            }
        });

        produk.setBackground(new java.awt.Color(0, 102, 102));
        produk.setForeground(new java.awt.Color(51, 255, 204));
        produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH KATEGORI" }));
        produk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                produkItemStateChanged(evt);
            }
        });
        produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produkActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Kategori          :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(buttonDeleteUser))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInsertUser, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonUpdateUser)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonInsertUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(fieldIdBuk, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(fieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(produk, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIdKat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIdBuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fieldJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldIdKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonInsertUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(buttonInsertUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateUserActionPerformed

    }//GEN-LAST:event_buttonUpdateUserActionPerformed

    private void buttonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteUserActionPerformed

    }//GEN-LAST:event_buttonDeleteUserActionPerformed

    private void buttonInsertUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertUserActionPerformed

    }//GEN-LAST:event_buttonInsertUserActionPerformed

    private void tableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBukuMouseClicked
        int lineTable = tableBuku.rowAtPoint(evt.getPoint());

        String idBuku = tableBuku.getValueAt(lineTable, 0).toString();
        fieldIdBuk.setText(idBuku);
        
        String idKat = tableBuku.getValueAt(lineTable, 0).toString();
        fieldIdKat.setText(idKat);

        String judul = tableBuku.getValueAt(lineTable, 2).toString();
        fieldJudul.setText(judul);

        String stok = tableBuku.getValueAt(lineTable, 3).toString();
        fieldStok.setText(stok);

        String harga = tableBuku.getValueAt(lineTable, 4).toString();
        fieldHarga.setText(harga);
        
        String pengarang = tableBuku.getValueAt(lineTable, 5).toString();
        fieldPengarang.setText(pengarang);
        
        buttonInsertUser.setEnabled(false);
        buttonDeleteUser.setEnabled(true);
        buttonUpdateUser.setEnabled(true);
    }//GEN-LAST:event_tableBukuMouseClicked

    private void fieldIdBukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdBukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdBukActionPerformed

    private void fieldJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJudulActionPerformed

    private void buttonInsertUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertUser1ActionPerformed
        new MainFrame().setVisible(true);
        setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonInsertUser1ActionPerformed

    private void produkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_produkItemStateChanged
        // TODO add your handling code here:
        Connection connection = null;
        Statement statement = null;
        String result = null;

        String showData = "SELECT * FROM kategori WHERE nama_kategori='" + produk.getSelectedItem() + "'";
        try {
            connection = Koneksi.getConnection();
            Statement stm = connection.createStatement();
            ResultSet res = stm.executeQuery(showData);
            while (res.next()) {
                fieldIdKat.setText(res.getString(5));
            }

        } catch (Exception ex) {
                Logger.getLogger(BukuFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_produkItemStateChanged

    private void produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuFrame().setVisible(true);
            }
        });
    }
    //Manage User Tab
//    private void insertUser() {
//        ObjectClass.bukuMod.insertObj2(fieldJudul.getText(), fieldPengarang.getText(),
//                fieldHarga.getText(), fieldStok.getText(), );
//
//        ObjectClass.bukuMod.insert(fieldJudul.getText(), fieldPengarang.getText(),
//                fieldHarga.getText(), fieldStok.getText());
//    }

//    private void updateUser() {
//        int index = tableBuku.getSelectedRow();
//        if (index == -1) {
//            return;
//        }
//        Buku usr = ObjectClass.bukuMod.getModelBuku(index);
//
////        usr.setId_user(fieldIdUser.getText());
//        usr.setNama_user(fieldNama.getText());
//        usr.setUsername(fieldUsername.getText());
//        usr.setPassword(fieldPassword.getText());
//        usr.setStatus(fieldStatus.getText());
//
//        ObjectClass.userMod.update(usr, index);
//
//        tableBuku.clearSelection();
//        buttonInsertUser.setEnabled(true);
//        buttonDeleteUser.setEnabled(false);
//        buttonUpdateUser.setEnabled(false);
//    }

    private void deleteUser() {
        int index = tableBuku.getSelectedRow();
        if (index == -1) {
            return;
        }
        ObjectClass.userMod.delete(index);

        tableBuku.clearSelection();
        buttonInsertUser.setEnabled(true);
        buttonDeleteUser.setEnabled(false);
        buttonUpdateUser.setEnabled(false);
    }
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteUser;
    private javax.swing.JButton buttonInsertUser;
    private javax.swing.JButton buttonInsertUser1;
    private javax.swing.JButton buttonUpdateUser;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldIdBuk;
    private javax.swing.JTextField fieldIdKat;
    private javax.swing.JTextField fieldJudul;
    private javax.swing.JTextField fieldPengarang;
    private javax.swing.JTextField fieldStok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> produk;
    private javax.swing.JTable tableBuku;
    // End of variables declaration//GEN-END:variables
}
